### ISSUE TITLE
Not building, npm error

### ISSUE THREAD

**Issue by northkode** [AlexDisler/cordova-icon#128]
on mac os high serria  

`fresh install npm install -g cordova-icon`

```Checking Project & Icon

  ✓  platforms found: android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for android


events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)```

**Comment by northkode** [comment]
ah you need image magic installed.. probably should have an error and warn the user to install.
