### ISSUE TITLE
Still have the same error

### ISSUE THREAD

**Issue by elepetit** [AlexDisler/cordova-icon#25]
Checking Project & Icon

  ✓  platforms found: ios
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by elepetit** [comment]
ok, just have to installe correctly imagemagick.....

issue closed

thx for all
