### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by MiLeung** [AlexDisler/cordova-icon#44]
Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/cordova-icon/index.js:101:44
    at Parser.<anonymous> (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/lib/xml2js.js:462:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/lib/xml2js.js:423:26)
    at emit (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/node_modules/sax/lib/sax.js:625:33)
    at emitNode (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/node_modules/sax/lib/sax.js:630:3)
    at closeTag (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/node_modules/sax/lib/sax.js:874:5)
    at Object.write (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/node_modules/sax/lib/sax.js:1202:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/cordova-icon/node_modules/xml2js/lib/xml2js.js:481:31)

**Comment by MiLeung** [comment]
imagemagick is installed

**Comment by BrunoCartier** [comment]
Hey,

What is your Node version (`node -v`)?

This could be an issue related to one of your XML files. If your try to run cordova-icon on a clean & new Cordova project, is the result the same?

**Comment by BrunoCartier** [comment]
Hey @MiLeung, any update on this? Did you fix the issue? Or found a workaround?

**Comment by MiLeung** [comment]
No still getting the same error

**Comment by BrunoCartier** [comment]
If your try to run cordova-icon on a clean & new Cordova project, is the result the same?
Could you please give us your `config.xml` file to see if something is wrong?

**Comment by BrunoCartier** [comment]
No response, closing. Feel free to re-open if needed.
