### ISSUE TITLE
Error: spawn convert ENOENT

### ISSUE THREAD

**Issue by pablodambrosio** [AlexDisler/cordova-icon#88]
MBP-de-Pablo:cordova-app pablo$ cordova-icon 

 Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by BrunoCartier** [comment]
Hi,

Please ensure ImageMagick is correctly installed and available. See README and other issues.

**Comment by neogero** [comment]
I had the same problem and it was a problem with ImageMagick installation. @pablodambrosio, you should reinstall ImagicMagick and be sure that option **Install legacy utilities(e.g. convert)** it's selected, your problem will be solved.
